### ISSUE TITLE
feature request: commandline world id extractor

### ISSUE THREAD

**Issue by lllXlll** [spinclick/wld2txt#1]
hello, i see you created a really advanced program here.

Can i make a tool request? The tool should be commandline and should be able to dump the world id of a .wld file, the syntax should be "towid.exe 'C:\Users\PC\Documents\My Games\Terraria\Worlds\worldname.wld' 'C:\Users\PC\Documents\My Games\Terraria\Worlds\output.txt'".

Can you do that? Thx! I couldn't find a way to contact you on any other medium or via mail, so i posted it here, i hope that doesn't bother you. If you want to do it and release it private, i would also pay the efford :) you can contact me at reddit (/u/Blubbll) or at discord or here or via mail. thx

**Comment by jnlon** [comment]
I considered making something like this back when wld2txt was in its early stages, since I needed to query all kinds of information about the world anyway.

Check out [this new repository](https://github.com/spinclick/wldquery). It shouldn't take too long to create this kind of tool, since wld2txt already does the heavy lifting.

**Comment by jnlon** [comment]
wldquery should do what you want now.

Read here first: https://github.com/spinclick/wldquery

Download here (Windows 64 bit): https://github.com/spinclick/wldquery/releases

The syntax is a bit different from your example. To accomlish the same thing, you would do:

wldquery.exe 'C:\Users\PC\Documents\My Games\Terraria\Worlds\worldname.wld' world_id > 'C:\Users\PC\Documents\My Games\Terraria\Worlds\output.txt'"

Note that the '>' is [shell redirection](https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/redirection.mspx), which will only work if you are running from cmd.exe or another commandline shell.

If you can't run wldquery.exe from a shell for some reason and still need the file output option, let me know by opening a new issue on the wldquery repository and I'll add a file output command switch.
